version: '3'
services:
  emqx:
    image: emqx/emqx:latest
    ports:
      - "18083:18083" # Dashboard port
      - "1883:1883"   # MQTT tcp port
      - "8883:8883"   # MQTT ssl port
      - "8083:8083"   # WB tcp port
      - "8084:8084"   # WB ssl port
